server.port=8084

# =========================
# Database - MariaDB
# =========================
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://180.93.144.96:3306/mt5_tool
spring.datasource.username=root
spring.datasource.password=app#basic@123

# =========================
# JPA
# =========================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# =========================
# Upload
# =========================
spring.web.resources.static-locations=classpath:/static/,file:uploads/
upload.path=uploads

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB